name: Test

on: push

env:
  SLURM_CONF: /etc/slurm/slurm.conf

jobs:
  install-test-esis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: get slurm configfiles
        uses: actions/checkout@v3
        with: 
          repository: daknuett/esis
          path: esis_for_configfiles
          branch: github_actions

      - name: install slurm
        run: |
          sudo apt-get update
          sudo apt-get install -y slurm-wlm
          cat esis_for_configfiles/.github/workflows/assets/slurm.conf | sed -e "s/main-kek/$(hostname)/" > esis_for_configfiles/.github/workflows/assets/slurm.conf
          cat esis_for_configfiles/.github/workflows/assets/slurm.conf
          sudo cp esis_for_configfiles/.github/workflows/assets/slurm.conf $SLURM_CONF
          sudo cp esis_for_configfiles/.github/workflows/assets/cgroup.conf /usr/local/etc/cgroup.conf
          sudo cp esis_for_configfiles/.github/workflows/assets/cgroup.conf /etc/slurm/cgroup.conf
          sudo mkdir -p /var/run/slurm/state/slurmd
          sudo chown slurm:slurm -R /var/run/slurm
          sudo chown slurm:slurm $SLURM_CONF
          sudo chown slurm:slurm /etc/slurm/cgroup.conf
          cat /etc/slurm/cgroup.conf

      - name: start slurm
        run: |
          sudo systemctl start slurmctld slurmd 
          sudo journalctl -u slurmctld
          sudo systemctl status slurmctld
          sudo journalctl -u slurmd
          sudo systemctl status slurmd
          sinfo
          scontrol show node
          while [[ $(sinfo | grep unk) != "" ]]; do echo "node state unk"; sudo cat /var/log/slurmd.log; sleep 1; done
          sinfo
          scontrol show node

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: update pip 
        run: |
          python -m pip install --upgrade pip

      - name: get esis
        uses: actions/checkout@v3
        with: 
          repository: daknuett/esis
          path: esis

      - name: install esis
        run: |
          cd esis
          python -m pip install .
          cd ..

      - name: install test dependencies
        run: |
          python -m pip install numpy

      - name: 01_simple_run
        run: |
          cd esis/
          cd runnable_tests/01_simple_run/
          ./setup_example.sh
          esis setup setup.sh sbatch_template.sh extract_mass.py generate_parameters.py
          esis run

          while [[ $(squeue -o %j | grep "01_s") != "" ]]; do squeue; sinfo; sudo cat /var/log/slurmd.log; scontrol show node; sleep 1; done

          wd=$(esis list | grep wrkdir)

          ls $wd/output/mass.0.npy
          ls $wd/output/mass.1.npy
          ls $wd/output/mass.2.npy
          ls $wd/output/mass.3.npy


