name: Test

on: push

env:
  SLURM_CONF: /etc/slurm/slurm.conf

jobs:
  install-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: get slurm configfiles
        uses: actions/checkout@v3
        with: 
          repository: daknuett/esis
          path: esis_for_configfiles
          branch: github_actions

      - name: install slurm
        run: |
          sudo apt-get update
          sudo apt-get install -y slurm-wlm
          cat esis_for_configfiles/.github/workflows/assets/slurm.conf | sed -e "s/main-kek/$(hostname)/" > esis_for_configfiles/.github/workflows/assets/slurm.conf
          cat esis_for_configfiles/.github/workflows/assets/slurm.conf
          sudo cp esis_for_configfiles/.github/workflows/assets/slurm.conf $SLURM_CONF
          sudo cp esis_for_configfiles/.github/workflows/assets/cgroup.conf /usr/local/etc/cgroup.conf
          sudo mkdir -p /var/run/slurm/state/slurmd
          sudo chown slurm:slurm -R /var/run/slurm
          sudo chown slurm:slurm $SLURM_CONF

      - name: start slurm
        run: |
          sudo systemctl start slurmctld slurmd 
          sudo journalctl -u slurmctld
          sudo systemctl status slurmctld
          sudo journalctl -u slurmd
          sudo systemctl status slurmd
          sinfo

  install-test-esis:
    needs: install-slurm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: update pip 
        run: |
          python -m pip install --upgrade pip

      - name: get esis
        uses: actions/checkout@v3
        with: 
          repository: daknuett/esis
          path: esis

      - name: install esis
        run: |
          cd esis
          python -m pip install .
          cd ..

      - name: 01_simple_run
        run: |
          cd esis/
          cd runnable_tests/01_simple_run/
          ./setup_example.sh
          esis setup setup.sh sbatch_template.sh extract_mass.py generate_parameters.py
          esis run
          esis list



