name: Test

on: push

env:
  SLURM_CONF: /etc/slurm/slurm.conf

jobs:
  install-test-esis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: get slurm configfiles
        uses: actions/checkout@v3
        with: 
          repository: daknuett/esis
          path: esis_for_configfiles

      - name: install slurm
        run: |
          sudo apt-get update
          sudo apt-get install -y slurm-wlm
          cat esis_for_configfiles/.github/workflows/assets/slurm.conf | sed -e "s/main-kek/$(hostname)/" > esis_for_configfiles/.github/workflows/assets/slurm.conf
          cat esis_for_configfiles/.github/workflows/assets/slurm.conf
          sudo cp esis_for_configfiles/.github/workflows/assets/slurm.conf $SLURM_CONF
          sudo cp esis_for_configfiles/.github/workflows/assets/cgroup.conf /usr/local/etc/cgroup.conf
          sudo cp esis_for_configfiles/.github/workflows/assets/cgroup.conf /etc/slurm/cgroup.conf
          sudo mkdir -p /var/run/slurm/state/slurmd
          sudo chown slurm:slurm -R /var/run/slurm
          sudo chown slurm:slurm $SLURM_CONF
          sudo chown slurm:slurm /etc/slurm/cgroup.conf
          cat /etc/slurm/cgroup.conf

      - name: start slurm
        run: |
          sudo systemctl start slurmctld slurmd 
          #sudo journalctl -u slurmctld
          #sudo systemctl status slurmctld
          #sudo journalctl -u slurmd
          #sudo systemctl status slurmd
          sinfo
          scontrol show node
          while [[ $(sinfo | grep unk) != "" ]]; do echo "node state unk"; sudo cat /var/log/slurmd.log; sleep 1; done
          sinfo
          scontrol show node

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: update pip 
        run: |
          python -m pip install --upgrade pip

      - name: get esis
        uses: actions/checkout@v3
        with: 
          repository: daknuett/esis
          path: esis

      - name: install esis
        run: |
          cd esis
          python -m pip install .
          cd ..

      - name: install test dependencies
        run: |
          python -m pip install numpy

      - name: 01_simple_run
        run: |
          cd esis/
          cd runnable_tests/01_simple_run/
          ./setup_example.sh
          esis setup setup.sh sbatch_template.sh extract_mass.py generate_parameters.py
          esis run

          #while [[ $(squeue -o %j | grep "01_s") != "" ]]; do squeue; sinfo; sudo cat /var/log/slurmd.log; scontrol show node; sleep 1; done
          while [[ $(squeue -o %j | grep "01_s") != "" ]]; do squeue; sleep 1; done

          wd=$(esis list | grep wrkdir)

          ls $wd/output/mass.0.npy
          ls $wd/output/mass.1.npy
          ls $wd/output/mass.2.npy
          ls $wd/output/mass.3.npy
          cd ../../..


      - name: 02_dependencies
        run: |
          cd esis/
          cd runnable_tests/02_dependencies/

          cd A_prepare_data/
          esis setup setup.sh sbatch_template.sh produce_data.py generate_parameters.py
          cd ..
          
          cd B_analyze_data/
          esis setup setup.sh sbatch_template.sh extract_mass.py generate_parameters.py
          esis require ../A_prepare_data/wf.esis2.json data_generation

          esis dependency


          #while [[ $(squeue -o %j | grep "01_s") != "" ]]; do squeue; sinfo; sudo cat /var/log/slurmd.log; scontrol show node; sleep 1; done
          while [[ $(squeue -o %j | grep "02_B_") != "" ]]; do squeue; sleep 1; done

          wd=$(esis list | grep wrkdir)

          ls $wd/output/mass.0.npy
          ls $wd/output/mass.1.npy
          ls $wd/output/mass.2.npy
          ls $wd/output/mass.3.npy

          cd ../../../..

      - name: 03_checkpointing
        run: |
          cd esis/
          cd runnable_tests/03_checkpointing

          esis setup setup.sh sbatch_template.sh train_operator.py generate_parameters.py
          esis run
          wd=$(esis list | grep wrkdir)
          cd $wd
          while [[ $(squeue -o %j | grep "03_ch") != "" ]]; do squeue; sleep 1; done

          cat cwd/slurm*
          pwd
          ls
          ls __checkpoints__
          python ../check_results.py

          cd ../../../..

      - name: 04_iterative_checkpointing
        run: |
          cd esis/
          cd runnable_tests/04_iterative_checkpointing

          esis setup setup.sh sbatch_template.sh train_operator.py generate_parameters.py
          esis run
          wd=$(esis list | grep wrkdir)
          cd $wd
          while [[ $(squeue -o %j | grep "04_it") != "" ]]; do squeue; sleep 1; done

          cat cwd/slurm*
          pwd
          ls
          ls __checkpoints__
          python ../check_results.py

          cd ../../../..

      - name: 05_chpt_load
        run: |
          cd esis/
          cd runnable_tests/05_chpt_load/

          cd A_train
          esis setup setup.sh sbatch_template.sh train_operator.py generate_parameters.py ../includes/alphas.json
          cd ..
          cd B_test
          esis setup setup.sh sbatch_template.sh test_operator.py generate_parameters.py ../includes/alphas.json
          esis require ../A_train/wf.esis2.json trained_weights

          esis dependency
          while [[ $(squeue -o %j | grep "05_B_") != "" ]]; do squeue; cat wrkdir*/cwd/* || echo "waiting"; cat ../A_train/wrkdir*/cwd/* || echo "waiting"; sleep 1; done

          wd=$(esis list | grep wrkdir)
          cat ../A_train/wrkdir*/cwd/*
          cat $wd/cwd/*

          ls $wd/cwd/error.0.csv
          ls $wd/cwd/error.1.csv


          cd ../../../..
